jobmanager.rpc.address: flink-jobmanager
jobmanager.rpc.port: 6123
jobmanager.memory.process.size: 1024m
taskmanager.memory.process.size: 2048m
taskmanager.numberOfTaskSlots: 4
parallelism.default: 1
rest.port: 8081
rest.address: 0.0.0.0
blob.server.port: 6124
taskmanager.rpc.port: 6122
state.backend: rocksdb
fs.allowed-fallback-filesystems: s3a
state.checkpoints.dir: s3a://flink-checkpoints/checkpoints
state.savepoints.dir: s3a://flink-checkpoints/savepoints
execution.checkpointing.interval: 60000
execution.checkpointing.min-pause: 30000
execution.checkpointing.externalized-checkpoint-retention: RETAIN_ON_CANCELLATION
s3.endpoint: http://minio:9000
s3.path-style-access: true
